spring.application.name=finsight-ai

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.format=json
spring.ai.ollama.chat.options.temperature=0.1
spring.ai.ollama.chat.options.top-p=0.9
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Chroma Configuration
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.collection-name=financial-docs

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600

# Logging
logging.level.com.finsight.finsight_ai.service.ChatService=DEBUG

spring.ai.tesseract.library.path=/opt/homebrew/lib

tavily.api.key=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