spring.application.name=finsight-ai

# Claude Configuration
spring.ai.bedrock.aws.region=us-east-1

spring.ai.bedrock.converse.chat.options.model=us.anthropic.claude-3-5-haiku-20241022-v1:0
spring.ai.bedrock.converse.chat.options.temperature=0.1
spring.ai.bedrock.converse.chat.options.max-tokens=4000
spring.ai.bedrock.embedding.model=amazon.titan-embed-text-v2:0
spring.ai.bedrock.titan.embedding.enabled=true
spring.ai.bedrock.cohere.embedding.enabled=false

# Chroma Configuration
spring.ai.vectorstore.chroma.host=localhost
spring.ai.vectorstore.chroma.port=8000
spring.ai.vectorstore.chroma.collection-name=financial-docs
spring.ai.vectorstore.chroma.tenant-id=default_tenant
spring.ai.vectorstore.chroma.database-id=default_db

# CORS Configuration
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600
spring.ai.bedrock.titan.embedding.model=amazon.titan-embed-text-v2:0

# Logging
logging.level.com.finsight.finsight_ai.service.ChatService=DEBUG

spring.ai.tesseract.library.path=/opt/homebrew/lib

tavily.api.key=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
# This stops Ollama from competing to be the default ChatModel


#AWS Configuration
AWS_PROFILE=Restricted-limited-admin-877969058937